/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.PedidoControlador;
import controlador.UsuarioControlador;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.PedidoDTO;
import modelo.UsuarioDTO;

/**
 *
 * @author ESTEFANIAHURTADOOSPI
 */
public class CrearPedidoVista extends javax.swing.JFrame {

    /**
     * Creates new form CreacionPedidoVista
     */
    public CrearPedidoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        UsuarioControlador usuarioControlador = new UsuarioControlador();
        ArrayList<UsuarioDTO> empleados = usuarioControlador.consultarUsuariosPorRol("Empleado");
        DefaultComboBoxModel comboEmpleados = new DefaultComboBoxModel();
        cmbEmpleados.setModel(comboEmpleados);
        
        // Setear los empleados al comboEmpleados
        comboEmpleados.addElement(null);
        for (UsuarioDTO empleadoDTO : empleados) {
            comboEmpleados.addElement(empleadoDTO);
        }
        
        ArrayList<UsuarioDTO> funcionarios = usuarioControlador.consultarUsuariosPorRol("Funcionario");
        DefaultComboBoxModel comboFuncionarios = new DefaultComboBoxModel();
        cmbFuncionarios.setModel(comboFuncionarios);
     
        // Setear los funcionarios al comboFuncionarios
        comboFuncionarios.addElement(null);
        for (UsuarioDTO funcionarioDTO : funcionarios) {
            comboFuncionarios.addElement(funcionarioDTO);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidad = new javax.swing.JLabel();
        lblPresentacion = new javax.swing.JLabel();
        lblTipoEnvio = new javax.swing.JLabel();
        lblCiudadOrigen = new javax.swing.JLabel();
        lblCiudadDestino = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        lblFechaEnvio = new javax.swing.JLabel();
        lblFechaEstimada = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPresentacion = new javax.swing.JTextField();
        txtCiudadOrigen = new javax.swing.JTextField();
        txtCiudadDestino = new javax.swing.JTextField();
        txtFechaEnvio = new javax.swing.JTextField();
        txtFechaEstimada = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        cbxTipoEnvio = new javax.swing.JComboBox<>();
        cbxTipoPago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbEmpleados = new javax.swing.JComboBox<>();
        cmbFuncionarios = new javax.swing.JComboBox<>();
        lblFechaEstimada1 = new javax.swing.JLabel();
        lblFechaEstimada2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidad");

        lblPresentacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPresentacion.setText("Presentación");

        lblTipoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoEnvio.setText("Tipo de envío");

        lblCiudadOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCiudadOrigen.setText("Ciudad de origen");

        lblCiudadDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCiudadDestino.setText("Ciudad destino");

        lblTipoPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoPago.setText("Tipo de pago");

        lblFechaEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEnvio.setText("Fecha de envío");

        lblFechaEstimada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEstimada.setText("Fecha estimada");

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpleado.setText("Empleado");

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuncionario.setText("Funcionario");

        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrear.setText("Crear pedido");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenu.setText("Menú principal");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        cbxTipoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxTipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MARITIMO", "TERRESTRE", "AEREO" }));

        cbxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "EFECTIVO", "CREDITO", "DEBITO", "PSE" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPORTACIONES ESTEFANIA");

        cmbEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpleadosActionPerformed(evt);
            }
        });

        lblFechaEstimada1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEstimada1.setText("(yyyy-mm-dd)");

        lblFechaEstimada2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEstimada2.setText("(yyyy-mm-dd)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPresentacion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblTipoEnvio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCiudadOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCiudadDestino)
                            .addComponent(lblTipoPago))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCiudadDestino)
                            .addComponent(cbxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaEstimada)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(txtFechaEstimada)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmpleado)
                                        .addComponent(lblFuncionario))
                                    .addGap(73, 73, 73)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(lblFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaEstimada2)
                            .addComponent(lblFechaEstimada1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPresentacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxTipoEnvio, javax.swing.GroupLayout.Alignment.LEADING, 0, 215, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPresentacion)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEnvio)
                    .addComponent(cbxTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudadOrigen)
                    .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudadDestino)
                    .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPago)
                    .addComponent(cbxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEnvio)
                    .addComponent(txtFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaEstimada2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEstimada)
                    .addComponent(txtFechaEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaEstimada1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpleado)
                            .addComponent(cmbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuncionario)
                            .addComponent(cmbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new PrincipalVista().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        PedidoDTO pedidoDTO = new PedidoDTO();
        
        pedidoDTO.setCantidad(Integer.parseInt(txtCantidad.getText()));
        pedidoDTO.setPresentacion(txtPresentacion.getText());
        pedidoDTO.setTipoEnvio(cbxTipoEnvio.getSelectedItem().toString());
        pedidoDTO.setCiudadOrigen(txtCiudadOrigen.getText());
        pedidoDTO.setCiudadDestino(txtCiudadDestino.getText());
        pedidoDTO.setTipoPago(cbxTipoPago.getSelectedItem().toString());
        
        // Manejo de Fechas
        // Define el formato de la cadena
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            // Parsea la cadena y obtén un objeto Date
            pedidoDTO.setFechaEnvio( dateFormat.parse(txtFechaEnvio.getText()));
            pedidoDTO.setFechaEstimadaEntrega(dateFormat.parse(txtFechaEstimada.getText()));
        } catch (Exception e) {
            System.out.println("Hubo un error al convertir la cadena en Date: " + e.getMessage());
        }
        
        // Manejo datos de los Usuarios
        UsuarioDTO empleadoDTO = (UsuarioDTO) cmbEmpleados.getSelectedItem();
        pedidoDTO.setEmpleadoID(empleadoDTO.getId());
        
        UsuarioDTO funcionarioDTO = (UsuarioDTO) cmbFuncionarios.getSelectedItem();
        pedidoDTO.setFuncionarioID(funcionarioDTO.getId());
        
        PedidoControlador pedidoControlador = new PedidoControlador();
        
        boolean exito = pedidoControlador.crearPedido(pedidoDTO);

        if (exito) {
            // El pedido se creó con éxito
            JOptionPane.showMessageDialog(this, "Pedido creado con éxito");
            new ListaPedidosVista().setVisible(true);
            this.dispose();            
        } else {
            // Hubo un error al crear el pedido
            JOptionPane.showMessageDialog(this, "No se pudo crear el pedido");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    
    
    private void cmbEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPedidoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cbxTipoEnvio;
    private javax.swing.JComboBox<String> cbxTipoPago;
    private javax.swing.JComboBox<UsuarioDTO> cmbEmpleados;
    private javax.swing.JComboBox<String> cmbFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCiudadDestino;
    private javax.swing.JLabel lblCiudadOrigen;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaEnvio;
    private javax.swing.JLabel lblFechaEstimada;
    private javax.swing.JLabel lblFechaEstimada1;
    private javax.swing.JLabel lblFechaEstimada2;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblPresentacion;
    private javax.swing.JLabel lblTipoEnvio;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtCiudadOrigen;
    private javax.swing.JTextField txtFechaEnvio;
    private javax.swing.JTextField txtFechaEstimada;
    private javax.swing.JTextField txtPresentacion;
    // End of variables declaration//GEN-END:variables
}
