/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.PedidoControlador;
import controlador.UsuarioControlador;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.PedidoDTO;
import modelo.UsuarioDTO;

/**
 *
 * @author estefania
 */
public class EditarPedidoVista extends javax.swing.JFrame {

    private int id;
    public EditarPedidoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidad = new javax.swing.JLabel();
        lblPresentacion = new javax.swing.JLabel();
        lblTipoEnvio = new javax.swing.JLabel();
        lblCiudadOrigen = new javax.swing.JLabel();
        lblCiudadDestino = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        lblFechaEnvio = new javax.swing.JLabel();
        lblFechaEstimada = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFuncioario = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPresentacion = new javax.swing.JTextField();
        txtCiudadOrigen = new javax.swing.JTextField();
        txtCiudadDestino = new javax.swing.JTextField();
        txtFechaEnvio = new javax.swing.JTextField();
        txtFechaEstimada = new javax.swing.JTextField();
        cbxTipoEnvio = new javax.swing.JComboBox<>();
        cbxTipoPago = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cmbEmpleados = new javax.swing.JComboBox<>();
        cmbFuncionarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidad");

        lblPresentacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPresentacion.setText("Presentación");

        lblTipoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoEnvio.setText("Tipo envio");

        lblCiudadOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCiudadOrigen.setText("Ciudad origen");

        lblCiudadDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCiudadDestino.setText("Ciudad destino");

        lblTipoPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoPago.setText("Tipo pago");

        lblFechaEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEnvio.setText("Fecha envío");

        lblFechaEstimada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaEstimada.setText("Fecha estimada de entrega");

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpleado.setText("Empleado");

        lblFuncioario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuncioario.setText("Funcionario");

        cbxTipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MARITIMO", "TERRESTRE", "AEREO" }));

        cbxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "EFECTIVO", "CREDITO", "DEBITO", "PSE" }));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPORTACIONES ESTEFANIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad)
                    .addComponent(lblPresentacion)
                    .addComponent(lblCiudadOrigen)
                    .addComponent(lblCiudadDestino)
                    .addComponent(lblFechaEnvio)
                    .addComponent(lblEmpleado)
                    .addComponent(lblFechaEstimada)
                    .addComponent(lblFuncioario)
                    .addComponent(lblTipoEnvio)
                    .addComponent(lblTipoPago))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad)
                    .addComponent(txtPresentacion)
                    .addComponent(txtCiudadOrigen)
                    .addComponent(txtCiudadDestino)
                    .addComponent(txtFechaEnvio)
                    .addComponent(txtFechaEstimada)
                    .addComponent(cbxTipoEnvio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTipoPago, 0, 190, Short.MAX_VALUE)
                    .addComponent(cmbEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPresentacion)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoEnvio)
                    .addComponent(cbxTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudadOrigen)
                    .addComponent(txtCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCiudadDestino)
                    .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoPago)
                    .addComponent(cbxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEnvio)
                    .addComponent(txtFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEstimada)
                    .addComponent(txtFechaEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmpleado)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFuncioario)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setIdPedido(int idP) throws SQLException
    {
        this.id=idP;
        mapearPedido();
           }
 private void mapearPedido()throws SQLException{
        PedidoControlador pedidoControlador = new PedidoControlador();

        PedidoDTO pedidoDTO = pedidoControlador.consultarPedidoId(this.id);
        
                
        txtCantidad.setText(String.valueOf(pedidoDTO.getCantidad()));
        txtPresentacion.setText(pedidoDTO.getPresentacion());
        cbxTipoEnvio.setSelectedItem(pedidoDTO.getTipoEnvio());
        txtCiudadOrigen.setText(pedidoDTO.getCiudadOrigen());
        txtCiudadDestino.setText(pedidoDTO.getCiudadDestino());
        cbxTipoPago.setSelectedItem(pedidoDTO.getTipoPago());

        // Manejo de Fechas
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        txtFechaEnvio.setText(dateFormat.format(pedidoDTO.getFechaEnvio()));
        txtFechaEstimada.setText(dateFormat.format(pedidoDTO.getFechaEstimadaEntrega()));

         //Manejo de combos empleados y usuario
        UsuarioControlador usuarioControlador = new UsuarioControlador();
        ArrayList<UsuarioDTO> empleados = usuarioControlador.consultarUsuariosPorRol("Empleado");
        DefaultComboBoxModel comboEmpleados = new DefaultComboBoxModel();
        cmbEmpleados.setModel(comboEmpleados);
        
        // Setear los empleados al comboEmpleados
        comboEmpleados.addElement(null);
        for (UsuarioDTO empleadoDTO : empleados) {
            comboEmpleados.addElement(empleadoDTO);
            if  (empleadoDTO.getId() == pedidoDTO.getEmpleadoID()) {
                cmbEmpleados.setSelectedItem(empleadoDTO);
            }
        }
        
        
        ArrayList<UsuarioDTO> funcionarios = usuarioControlador.consultarUsuariosPorRol("Funcionario");
        DefaultComboBoxModel comboFuncionarios = new DefaultComboBoxModel();
        cmbFuncionarios.setModel(comboFuncionarios);
     
        // Setear los funcionarios al comboFuncionarios
        comboFuncionarios.addElement(null);
        for (UsuarioDTO funcionarioDTO : funcionarios) {
            comboFuncionarios.addElement(funcionarioDTO);            
            if (funcionarioDTO.getId() == pedidoDTO.getFuncionarioID()) {
                cmbFuncionarios.setSelectedItem(funcionarioDTO);
            }
        }
        
        
        
        
        
        

    }
         
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        PedidoDTO pedidoDTO = new PedidoDTO();
        
        pedidoDTO.setId(this.id);
        pedidoDTO.setCantidad(Integer.parseInt(txtCantidad.getText()));
        pedidoDTO.setPresentacion(txtPresentacion.getText());
        pedidoDTO.setTipoEnvio(cbxTipoEnvio.getSelectedItem().toString());
        pedidoDTO.setCiudadOrigen(txtCiudadOrigen.getText());
        pedidoDTO.setCiudadDestino(txtCiudadDestino.getText());
        pedidoDTO.setTipoPago(cbxTipoPago.getSelectedItem().toString());
        
        // Manejo de Fechas
        // Define el formato de la cadena
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            // Parsea la cadena y obtén un objeto Date
            pedidoDTO.setFechaEnvio( dateFormat.parse(txtFechaEnvio.getText()));
            pedidoDTO.setFechaEstimadaEntrega(dateFormat.parse(txtFechaEstimada.getText()));
        } catch (Exception e) {
            System.out.println("Hubo un error al convertir la cadena en Date: " + e.getMessage());
        }
        
        // Manejo datos de los Usuarios
        UsuarioDTO empleadoDTO = (UsuarioDTO) cmbEmpleados.getSelectedItem();
        pedidoDTO.setEmpleadoID(empleadoDTO.getId());
        
        UsuarioDTO funcionarioDTO = (UsuarioDTO) cmbFuncionarios.getSelectedItem();
        pedidoDTO.setFuncionarioID(funcionarioDTO.getId());
        
        PedidoControlador pedidoControlador = new PedidoControlador();
        
        boolean exito = pedidoControlador.crearPedido(pedidoDTO);

        if (exito) {
            // El pedido se creó con éxito
            JOptionPane.showMessageDialog(this, "Pedido actualizado con éxito");
            new ListaPedidosVista().setVisible(true);
            this.dispose();            
        } else {
            // Hubo un error al crear el pedido
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el pedido");
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new ListaPedidosVista().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPedidoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxTipoEnvio;
    private javax.swing.JComboBox<String> cbxTipoPago;
    private javax.swing.JComboBox<String> cmbEmpleados;
    private javax.swing.JComboBox<String> cmbFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCiudadDestino;
    private javax.swing.JLabel lblCiudadOrigen;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaEnvio;
    private javax.swing.JLabel lblFechaEstimada;
    private javax.swing.JLabel lblFuncioario;
    private javax.swing.JLabel lblPresentacion;
    private javax.swing.JLabel lblTipoEnvio;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtCiudadOrigen;
    private javax.swing.JTextField txtFechaEnvio;
    private javax.swing.JTextField txtFechaEstimada;
    private javax.swing.JTextField txtPresentacion;
    // End of variables declaration//GEN-END:variables
}
