/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.PedidoControlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PedidoDTO;

/**
 *
 * @author ESTEFANIAHURTADOOSPI
 */
public class ListaPedidosVista extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
    /**
     * Creates new form ListaPedidosVista
     */
    public ListaPedidosVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Se colocan los nombres de la columnas que va a tener la tabla que se muestra al usuario en la pagina de Ver Pedidos.
        String[] titulos_tabla = {
            "ID", "Cantidad", "Presentación", "Tipo de Envío", "Ciudad Origen", "Ciudad Destino", "Tipo de Pago", "Fecha de Envío", "Fecha Estimada de Entrega"};
        modelo = new DefaultTableModel(null, titulos_tabla);
        tPedidos.setModel(modelo);
        
        buscarYcolocarPedidosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tPedidos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCrearPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cantidad", "Presentación", "Tipo de envío", "Ciudad de origen", "Ciudad destino", "Tipo de pago", "Fecha de envio", "Fecha estimada entrega", "Empleado", "Funcionario"
            }
        ));
        jScrollPane1.setViewportView(tPedidos);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenu.setText("Menú principal");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPORTACIONES ESTEFANIA");

        btnCrearPedido.setText("Crear pedido");
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditar)
                .addGap(28, 28, 28)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnCrearPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnMenu)
                    .addComponent(btnCrearPedido))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new PrincipalVista().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        new EditarPedidoVista().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        CrearPedidoVista crearPedidoVista = new CrearPedidoVista();
        crearPedidoVista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Se procede a obtener el controlador.
        PedidoControlador pedidoControlador = new PedidoControlador();
        
        boolean flag = pedidoControlador.eliminarPedido(Integer.parseInt(tPedidos.getValueAt(tPedidos.getSelectedRow(),0).toString()));
        if (flag) {
            System.out.println("Borrado con exito");
            JOptionPane.showMessageDialog(null, "Pedido borrado con exito");
            int count = modelo.getRowCount();
            for (int i = 0; i< count; i++) {
                modelo.removeRow(0);
            }
            
            buscarYcolocarPedidosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Metodo privado para buscar los datos de los pedidos de la base de datos y 
     * posteriormente agregarlos a la tabla que se muestra al usuario.
     */
    private void buscarYcolocarPedidosEnTabla() {
        // Se procede a obtener del controlador la informacion de tabla pedidos de la base de datos.
        PedidoControlador pedidoControlador = new PedidoControlador();
        
        ArrayList<PedidoDTO> pedidoDTOs = pedidoControlador.consultarPedidos();
        // Se itera uno a uno los datos encontrados en la tabla Pedidos de la base de datos y se agregan las filas (Rows) a la tabla que se muestra al usuario.
        for (PedidoDTO pedidoDTO : pedidoDTOs) {
            Object[] oPedido = {
                pedidoDTO.getId(), 
                pedidoDTO.getCantidad(), 
                pedidoDTO.getPresentacion(), 
                pedidoDTO.getTipoEnvio(), 
                pedidoDTO.getCiudadOrigen(), 
                pedidoDTO.getCiudadDestino(),
                pedidoDTO.getTipoPago(),
                pedidoDTO.getFechaEnvio(),
                pedidoDTO.getFechaEstimadaEntrega(),
                pedidoDTO.getEmpleadoID(),
                pedidoDTO.getFuncionarioID()
            };
            modelo.addRow(oPedido);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPedidosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPedidosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPedidosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPedidosVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPedidosVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPedidos;
    // End of variables declaration//GEN-END:variables
}
